default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: tiny_finds_app_development

test:
  <<: *default
  database: tiny_finds_app_test

production:
  <<: *default
  database: tiny_finds_app_production
  username: tiny_finds_app
  password: <%= ENV["TINY_FINDS_APP_DATABASE_PASSWORD"] %>
